<div class="fb-page" 
     data-href="<?php echo $this->getPageLink() ?>"
     data-tabs="<?php echo $this->getTabs() ?>"
     data-width="<?php echo $this->getWidth() ?>"
     data-height="<?php echo $this->getHeight() ?>"
     data-hide-cover="<?php echo $this->getHideCover() ?>"
     data-show-facepile="<?php echo $this->getShowFaces() ?>" 
     data-show-posts="<?php echo $this->getShowPosts() ?>"
     data-small-header="<?php echo $this->getSmallHeader() ?>"
     data-adapt-container-width="<?php echo $this->getAdaptContainerWidth() ?>"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3"; 
      //  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>