<!--
Magento Facebook Extension - emallfacebook
Copyright (C) 2012  SMDesign - www.smdesign.rs/www.extensionsmall.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

If you like our Extensions please keep the link at the bottom of widget.

-->

<?php
$facebookConfig = $this->getFacebookConfig();
$facebookConfigEnabled = ($facebookConfig['enabled']!='') ? $facebookConfig['enabled'] : '1';
$facebookConfigFacebookBoxSide = ($facebookConfig['facebook_box_side']!='') ? $facebookConfig['facebook_box_side'] : '1';
$facebookConfigFacebookFeed = ($facebookConfig['facebook_feed']!='') ? $facebookConfig['facebook_feed'] : 'https://www.facebook.com/extensionsmall';
$facebookConfigFacebookBoxTopPosition = $facebookConfig['facebook_box_top_position']!='' ? $facebookConfig['facebook_box_top_position'] : '50px';
$facebookConfigFacebookBoxWidth = ($facebookConfig['facebook_box_width']!='') ? $facebookConfig['facebook_box_width'] : '300';
$facebookConfigFacebookBoxHeight = ($facebookConfig['facebook_box_height']!='') ? $facebookConfig['facebook_box_height'] : '300';
$facebookConfigFacebookBoxBackground = ($facebookConfig['facebook_box_background']!='') ? $facebookConfig['facebook_box_background'] : '#333333';
$facebookConfigFacebookTheme = ($facebookConfig['facebook_theme']!='') ? $facebookConfig['facebook_theme'] : 'dark';
$facebookConfigFacebookShowfaces = ($facebookConfig['facebook_showfaces']!='') ? $facebookConfig['facebook_showfaces'] : 'true';
$facebookConfigFacebookDatastream = ($facebookConfig['facebook_datastream']!='') ? $facebookConfig['facebook_datastream'] : 'true';
$facebookConfigFacebookShowBorder = ($facebookConfig['facebook_showborder']!='') ? $facebookConfig['facebook_showborder'] : 'true';
$facebookConfigFacebookDataheader = ($facebookConfig['facebook_dataheader']!='') ? $facebookConfig['facebook_dataheader'] : 'false';
$facebookConfigFacebookForcewall = ($facebookConfig['facebook_forcewall']!='') ? $facebookConfig['facebook_forcewall'] : 'true';
?>
<?php if($facebookConfigEnabled == 1): ?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
	<style type="text/css">
		div.emallfacebook-wraper{
			z-index: 1000;
			position:fixed;
			top:<?php echo $facebookConfigFacebookBoxTopPosition ?>px;
            width: <?php echo $facebookConfigFacebookBoxWidth ?>px;
		}
		div.emallfacebook-wraper.left{
			left:0px;
		}
		div.emallfacebook-wraper.right{
			right:0px;
		}
		div#emallfacebook{
			float:left;
			background: <?php echo $facebookConfigFacebookBoxBackground ?>;
			opacity: 0.85;
		}
		div#emallfacebook label {
			color: <?php echo $facebookConfigFacebookTweetsColor ?>; 
			background: <?php echo $facebookConfigFacebookBoxBackground ?>;
			border-radius: 0 0 9px 9px !important;
			color: #FFFFFF;
			float: left;
			opacity: 0.85;
			padding: 5px;
			width: 96%;
		}
		.twtr-doc {
			border-radius: 5px 5px 0px 0px !important;
		}
		div#emallfacebook label a{
			text-decoration:none;
			color:<?php echo $facebookConfigFacebookTweetsLinkColor ?>;
		}
		div#emallfacebook label a:hover{
			text-decoration:underline;
		}
		div.emallfacebook-wraper.left div#emallfacebook{
			border-radius: 5px 5px 10px 10px;
			box-shadow: 3px 3px 10px <?php echo $facebookConfigFacebookBoxBackground ?>;
		}
		div.emallfacebook-wraper.right div#emallfacebook{
			border-radius: 10px 0 10px 10px;
			box-shadow: 0 4px 18px <?php echo $facebookConfigFacebookBoxBackground ?>;
		}
		#emallfacebook-open{
			background: #3e3e3e;
			background: <?php echo $facebookConfigFacebookBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emallfacebook/facebook-button.png") ?>) no-repeat 6px 6px <?php echo $facebookConfigFacebookBoxBackground ?>;
			color:<?php echo $facebookConfigFacebookTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			transition: all 0.1s ease 0.2s;
			height: 30px;
			width: 30px;
			padding: 6px;
		}
		.emallfacebook-wraper.right #emallfacebook-open.open {
			background: #3e3e3e;
			background: <?php echo $facebookConfigFacebookBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emallfacebook/facebook-button-hover.png") ?>) no-repeat 6px 6px <?php echo $facebookConfigFacebookBoxBackground ?>;
			color:<?php echo $facebookConfigFacebookTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			height: 30px;
			width: 90px;
			padding: 6px;
		}
		.emallfacebook-wraper.left #emallfacebook-open.open {
			background: #3e3e3e;
			background: <?php echo $facebookConfigFacebookBoxBackground ?>;
			background: url( <?php  echo $this->getSkinUrl("images/emallfacebook/facebook-button-hover.png") ?>) no-repeat 6px 6px <?php echo $facebookConfigFacebookBoxBackground ?> ;
			color:<?php echo $facebookConfigFacebookTweetsColor ?>; 
			display: inline-block;
			text-decoration: none;
			opacity: 0.8;
			height: 30px;
			width: 90px;
			padding: 6px;
		}
		#emallfacebook-open:hover { transition: all .2s; background: url( <?php  echo $this->getSkinUrl("images/emallfacebook/facebook-button-hover.png") ?>) no-repeat 6px 6px <?php echo $facebookConfigFacebookBoxBackground ?>; padding-left: 70px; }
		.emallfacebook-wraper.left #emallfacebook-open{
			border-radius: 0 27px 27px 0;
			margin-bottom: 1px;
		}
		.emallfacebook-wraper.right #emallfacebook-open{
			border-radius: 25px 0 0 27px;
			float: right;
			margin-bottom: 1px;
		}        
       
	</style>
	<script type="text/javascript">
		function createCookie(name,value,days) {
			if (days) {
				var date = new Date();
				date.setTime(date.getTime()+(days*24*60*60*1000));
				var expires = "; expires="+date.toGMTString();
			}
			else var expires = "";
			document.cookie = name+"="+value+expires+"; path=/";
		}
		function readCookie(name) {
			var nameEQ = name + "=";
			var ca = document.cookie.split(';');
			for(var i=0;i < ca.length;i++) {
				var c = ca[i];
				while (c.charAt(0)==' ') c = c.substring(1,c.length);
				if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
			}
			return null;
		}
		function eraseCookie(name) {
			createCookie(name,"",-1);
		}
		function setState(){
			if(readCookie('emalltwitt')==null){
				createCookie('emalltwitt','hide',1);
				$('emallfacebook-open').className="";
				$('emallfacebook-open').addClassName('close');
			} else {
				eraseCookie('emalltwitt');
				$('emallfacebook-open').className="";
				$('emallfacebook-open').addClassName('open');
			}
		}
		function checkCookie() {
			if(readCookie('emalltwitt')=='hide'){
				$('emallfacebook').hide();
			} else {
				$('emallfacebook-open').className="";
				$('emallfacebook-open').addClassName('open');
			}
		}
	</script>

	<div class="emallfacebook-wraper <?php if($facebookConfigFacebookBoxSide==1){ echo('left'); } else { echo('right'); } ;?>" id="emallfacebook-wraper">
		<a id="emallfacebook-open" onclick="$('emallfacebook').toggle('blind');  setState(); return false;" href="#">&nbsp;</a>
		<br />
		<div class="emallfacebook" id="emallfacebook">
			<div id="toggle">
			<div class="fb-like-box" 
            data-href="<?php echo $facebookConfigFacebookFeed?>" 
            data-width="<?php echo $facebookConfigFacebookBoxWidth ?>"
            data-height="<?php echo $facebookConfigFacebookBoxHeight ?>" 
            data-show-faces="<?php if($facebookConfigFacebookShowfaces==1){ echo('true'); } else { echo('false'); }?>" 
            data-colorscheme="<?php echo $facebookConfigFacebookTheme ?>" 
            data-stream="<?php if($facebookConfigFacebookDatastream==1){ echo('true'); } else { echo('false'); }?>" 
            data-show-border="<?php if($facebookConfigFacebookShowBorder==1){ echo('true'); } else { echo('false'); }?>" 
            data-header="<?php if($facebookConfigFacebookDataheader==1){ echo('true'); } else { echo('false'); }?>"
            data-force-wall="<?php if($facebookConfigFacebookForcewall==1){ echo('true'); } else { echo('false'); }?>"></div>
        
				<label>Provided by <a href="http://www.extensionsmall.com/" target="_blank"><span style="float: right; padding-right: 15px;">Extensions Mall</span></a></label>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		checkCookie();
	</script>
<?php endif; ?>

